name: ci

on:
  push:
    branches:
      - main
      - stage
      - dev
  pull_request:
    branches:
      - main
      - stage
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Prepare modules
        run: npm run root:prepare

      - name: Install root dependencies
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: [ setup ]

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    needs: [ setup, lint ]

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test


  build:
    runs-on: ubuntu-latest

    needs: [ setup, lint, test ]

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
